--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 28/07/2022 12:10:20
-- Server version: 8.0.29
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS `bitsion-ficticia-sa`;

CREATE DATABASE `bitsion-ficticia-sa`
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

--
-- Set default database
--
USE `bitsion-ficticia-sa`;

--
-- Create table `genero`
--
CREATE TABLE genero (
  idGenero int DEFAULT NULL,
  descripcion varchar(255) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `UK_genero_idGenero` on table `genero`
--
ALTER TABLE genero
ADD UNIQUE INDEX UK_genero_idGenero (idGenero);

--
-- Create table `cliente`
--
CREATE TABLE cliente (
  idCliente int NOT NULL AUTO_INCREMENT,
  nombre varchar(255) DEFAULT NULL,
  apellido varchar(255) DEFAULT NULL,
  dni varchar(255) DEFAULT NULL,
  edad int DEFAULT NULL,
  idGenero int DEFAULT NULL,
  maneja tinyint DEFAULT NULL,
  lentes tinyint DEFAULT NULL,
  diabetico tinyint DEFAULT NULL,
  enfermedades varchar(255) DEFAULT NULL,
  activo tinyint DEFAULT NULL,
  PRIMARY KEY (idCliente)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE cliente
ADD CONSTRAINT FK_cliente_idGenero FOREIGN KEY (idGenero)
REFERENCES genero (idGenero);

--
-- Create view `view1`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW view1
AS
SELECT
  `cliente`.`idCliente` AS `idCliente`,
  `cliente`.`nombre` AS `nombre`,
  `cliente`.`apellido` AS `apellido`,
  `cliente`.`dni` AS `dni`,
  `cliente`.`edad` AS `edad`,
  `genero`.`idGenero` AS `idGenero`,
  `genero`.`descripcion` AS `genero`,
  `cliente`.`maneja` AS `maneja`,
  `cliente`.`lentes` AS `lentes`,
  `cliente`.`diabetico` AS `diabetico`,
  `cliente`.`enfermedades` AS `enfermedades`,
  `cliente`.`activo` AS `activo`
FROM (`cliente`
  JOIN `genero`
    ON ((`cliente`.`idGenero` = `genero`.`idGenero`)))
WHERE (`cliente`.`activo` = 1);

-- 
-- Dumping data for table genero
--
INSERT INTO genero VALUES
(1, 'Hombre'),
(2, 'Mujer');

-- 
-- Dumping data for table cliente
--
INSERT INTO cliente VALUES
(1, 'Jose', 'Perez', '73859205', 30, 1, 0, 1, 1, 'No', 1),
(2, 'Mariana', 'Cecilia', '22036789', 50, 2, 0, 1, 0, 'No', 0),
(3, 'Lourdes', 'Sanchez', '63728304', 15, 2, 0, 1, 0, 'No', 1),
(4, NULL, NULL, NULL, 0, 1, 0, 0, 0, NULL, 0),
(5, 'Mariana', 'dfsafdsa', '22222', 0, 1, 0, 0, 0, NULL, 0),
(6, 'eee', 'eee', '2222', 0, 1, 0, 1, 0, NULL, 0),
(7, 'fsdafsda', 'fdsafsda', '2323', 1, 1, 1, 1, 1, 'fsdfdsa', 0),
(8, 'María', 'Fernandez', '83726304', 40, 2, 0, 1, 1, 'No', 1);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;